# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='final_project',
  syntax='proto2',
  serialized_pb=_b('\n\ndata.proto\x12\rfinal_project\"&\n\nTClientReq\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\"9\n\nTClientRsp\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x11\n\tfile_name\x18\x02 \x02(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x02(\t\"@\n\nTServerReq\x12\n\n\x02id\x18\x01 \x02(\x05\x12&\n\x04type\x18\x02 \x02(\x0e\x32\x18.final_project.PhoneType\"\x19\n\x0bTCMDCommand\x12\n\n\x02id\x18\x01 \x02(\x05\"V\n\rTFileTransfer\x12\n\n\x02id\x18\x01 \x02(\x05\x12\r\n\x05index\x18\x02 \x02(\x05\x12\x0c\n\x04size\x18\x03 \x02(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x02(\x0c\x12\x0e\n\x06isLast\x18\x05 \x02(\x05\".\n\nTFileStart\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x14\n\x0csize_of_data\x18\x02 \x02(\x05\"\x89\x01\n\nTServerRsp\x12\x30\n\ncmdCommand\x18\x01 \x01(\x0b\x32\x1a.final_project.TCMDCommandH\x00\x12\x34\n\x0c\x66ileTransfer\x18\x02 \x01(\x0b\x32\x1c.final_project.TFileTransferH\x00\x12\x0b\n\x02id\x18\xc8\x01 \x02(\x05\x42\x06\n\x04type\"\xce\x01\n\x05TData\x12.\n\tclientReq\x18\x01 \x01(\x0b\x32\x19.final_project.TClientReqH\x00\x12.\n\tclientRsp\x18\x02 \x01(\x0b\x32\x19.final_project.TClientRspH\x00\x12.\n\tserverReq\x18\x03 \x01(\x0b\x32\x19.final_project.TServerReqH\x00\x12.\n\tserverRsp\x18\x04 \x01(\x0b\x32\x19.final_project.TServerRspH\x00\x42\x05\n\x03Msg*+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04WORK\x10\x02')
)

_PHONETYPE = _descriptor.EnumDescriptor(
  name='PhoneType',
  full_name='final_project.PhoneType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOBILE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOME', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORK', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=706,
  serialized_end=749,
)
_sym_db.RegisterEnumDescriptor(_PHONETYPE)

PhoneType = enum_type_wrapper.EnumTypeWrapper(_PHONETYPE)
MOBILE = 0
HOME = 1
WORK = 2



_TCLIENTREQ = _descriptor.Descriptor(
  name='TClientReq',
  full_name='final_project.TClientReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='final_project.TClientReq.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='final_project.TClientReq.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=67,
)


_TCLIENTRSP = _descriptor.Descriptor(
  name='TClientRsp',
  full_name='final_project.TClientRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='final_project.TClientRsp.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='final_project.TClientRsp.file_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='final_project.TClientRsp.data', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=126,
)


_TSERVERREQ = _descriptor.Descriptor(
  name='TServerReq',
  full_name='final_project.TServerReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='final_project.TServerReq.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='final_project.TServerReq.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=192,
)


_TCMDCOMMAND = _descriptor.Descriptor(
  name='TCMDCommand',
  full_name='final_project.TCMDCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='final_project.TCMDCommand.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=219,
)


_TFILETRANSFER = _descriptor.Descriptor(
  name='TFileTransfer',
  full_name='final_project.TFileTransfer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='final_project.TFileTransfer.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='final_project.TFileTransfer.index', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='final_project.TFileTransfer.size', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='final_project.TFileTransfer.data', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isLast', full_name='final_project.TFileTransfer.isLast', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=307,
)


_TFILESTART = _descriptor.Descriptor(
  name='TFileStart',
  full_name='final_project.TFileStart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='final_project.TFileStart.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size_of_data', full_name='final_project.TFileStart.size_of_data', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=355,
)


_TSERVERRSP = _descriptor.Descriptor(
  name='TServerRsp',
  full_name='final_project.TServerRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmdCommand', full_name='final_project.TServerRsp.cmdCommand', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fileTransfer', full_name='final_project.TServerRsp.fileTransfer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='final_project.TServerRsp.id', index=2,
      number=200, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='final_project.TServerRsp.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=358,
  serialized_end=495,
)


_TDATA = _descriptor.Descriptor(
  name='TData',
  full_name='final_project.TData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientReq', full_name='final_project.TData.clientReq', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientRsp', full_name='final_project.TData.clientRsp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverReq', full_name='final_project.TData.serverReq', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverRsp', full_name='final_project.TData.serverRsp', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Msg', full_name='final_project.TData.Msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=498,
  serialized_end=704,
)

_TSERVERREQ.fields_by_name['type'].enum_type = _PHONETYPE
_TSERVERRSP.fields_by_name['cmdCommand'].message_type = _TCMDCOMMAND
_TSERVERRSP.fields_by_name['fileTransfer'].message_type = _TFILETRANSFER
_TSERVERRSP.oneofs_by_name['type'].fields.append(
  _TSERVERRSP.fields_by_name['cmdCommand'])
_TSERVERRSP.fields_by_name['cmdCommand'].containing_oneof = _TSERVERRSP.oneofs_by_name['type']
_TSERVERRSP.oneofs_by_name['type'].fields.append(
  _TSERVERRSP.fields_by_name['fileTransfer'])
_TSERVERRSP.fields_by_name['fileTransfer'].containing_oneof = _TSERVERRSP.oneofs_by_name['type']
_TDATA.fields_by_name['clientReq'].message_type = _TCLIENTREQ
_TDATA.fields_by_name['clientRsp'].message_type = _TCLIENTRSP
_TDATA.fields_by_name['serverReq'].message_type = _TSERVERREQ
_TDATA.fields_by_name['serverRsp'].message_type = _TSERVERRSP
_TDATA.oneofs_by_name['Msg'].fields.append(
  _TDATA.fields_by_name['clientReq'])
_TDATA.fields_by_name['clientReq'].containing_oneof = _TDATA.oneofs_by_name['Msg']
_TDATA.oneofs_by_name['Msg'].fields.append(
  _TDATA.fields_by_name['clientRsp'])
_TDATA.fields_by_name['clientRsp'].containing_oneof = _TDATA.oneofs_by_name['Msg']
_TDATA.oneofs_by_name['Msg'].fields.append(
  _TDATA.fields_by_name['serverReq'])
_TDATA.fields_by_name['serverReq'].containing_oneof = _TDATA.oneofs_by_name['Msg']
_TDATA.oneofs_by_name['Msg'].fields.append(
  _TDATA.fields_by_name['serverRsp'])
_TDATA.fields_by_name['serverRsp'].containing_oneof = _TDATA.oneofs_by_name['Msg']
DESCRIPTOR.message_types_by_name['TClientReq'] = _TCLIENTREQ
DESCRIPTOR.message_types_by_name['TClientRsp'] = _TCLIENTRSP
DESCRIPTOR.message_types_by_name['TServerReq'] = _TSERVERREQ
DESCRIPTOR.message_types_by_name['TCMDCommand'] = _TCMDCOMMAND
DESCRIPTOR.message_types_by_name['TFileTransfer'] = _TFILETRANSFER
DESCRIPTOR.message_types_by_name['TFileStart'] = _TFILESTART
DESCRIPTOR.message_types_by_name['TServerRsp'] = _TSERVERRSP
DESCRIPTOR.message_types_by_name['TData'] = _TDATA
DESCRIPTOR.enum_types_by_name['PhoneType'] = _PHONETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TClientReq = _reflection.GeneratedProtocolMessageType('TClientReq', (_message.Message,), dict(
  DESCRIPTOR = _TCLIENTREQ,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:final_project.TClientReq)
  ))
_sym_db.RegisterMessage(TClientReq)

TClientRsp = _reflection.GeneratedProtocolMessageType('TClientRsp', (_message.Message,), dict(
  DESCRIPTOR = _TCLIENTRSP,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:final_project.TClientRsp)
  ))
_sym_db.RegisterMessage(TClientRsp)

TServerReq = _reflection.GeneratedProtocolMessageType('TServerReq', (_message.Message,), dict(
  DESCRIPTOR = _TSERVERREQ,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:final_project.TServerReq)
  ))
_sym_db.RegisterMessage(TServerReq)

TCMDCommand = _reflection.GeneratedProtocolMessageType('TCMDCommand', (_message.Message,), dict(
  DESCRIPTOR = _TCMDCOMMAND,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:final_project.TCMDCommand)
  ))
_sym_db.RegisterMessage(TCMDCommand)

TFileTransfer = _reflection.GeneratedProtocolMessageType('TFileTransfer', (_message.Message,), dict(
  DESCRIPTOR = _TFILETRANSFER,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:final_project.TFileTransfer)
  ))
_sym_db.RegisterMessage(TFileTransfer)

TFileStart = _reflection.GeneratedProtocolMessageType('TFileStart', (_message.Message,), dict(
  DESCRIPTOR = _TFILESTART,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:final_project.TFileStart)
  ))
_sym_db.RegisterMessage(TFileStart)

TServerRsp = _reflection.GeneratedProtocolMessageType('TServerRsp', (_message.Message,), dict(
  DESCRIPTOR = _TSERVERRSP,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:final_project.TServerRsp)
  ))
_sym_db.RegisterMessage(TServerRsp)

TData = _reflection.GeneratedProtocolMessageType('TData', (_message.Message,), dict(
  DESCRIPTOR = _TDATA,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:final_project.TData)
  ))
_sym_db.RegisterMessage(TData)


# @@protoc_insertion_point(module_scope)
